apiVersion: v1
kind: Service
metadata:
    name: notification-service
spec:
    type: NodePort
    selector:
        app: notification-deployment
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30571
